// constants.ts

import { CardData, CardType, Rarity, Template } from "./types";

// Placeholder data URI for a simple gray frame.
const modernFrame =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXcAAAKtCAIAAACVz9xeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAABWSURBVHja7cExAQAAAMKg9U/tbwagAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC4N2kMAAE2lADsAAAAAElFTSuQmCC";
// Placeholder data URI for a simple purple frame.
const showcaseFrame =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXcAAAKtCAIAAACVz9xeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAB/SURBVHja7dJBAYAwEMDAwL9+aQ8eIIkd2bOzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4os+a+pt0+AZ+fvgEAAAAAAAAAAAAAAAAA+GU9cW89gP8d/30A+G09aAB4mAAA+GgBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAb2y4AAZ1LPAkAAAAASUVORK5CYII=";

export const AVAILABLE_FONTS = [
  { name: "Beleren", value: "Beleren, sans-serif" },
  { name: "MPlantin", value: "MPlantin, serif" },
  { name: "Title", value: "IM Fell English SC, serif" },
  { name: "Rounded", value: "M PLUS Rounded 1c, sans-serif" },
];

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: "modern",
    name: "Modern",
    frameImageUrl: modernFrame,
    elements: {
      title: { x: 5.5, y: 5, width: 55, height: 6 },
      manaCost: { x: 62, y: 5, width: 32, height: 6 },
      art: { x: 4.5, y: 12, width: 91, height: 46 },
      typeLine: { x: 5.5, y: 59, width: 75, height: 6 },
      setSymbol: { x: 84.5, y: 59.5, width: 10, height: 5 },
      textBox: { x: 5.5, y: 66, width: 89, height: 26 },
      ptBox: { x: 78, y: 88.5, width: 16, height: 6 },
      collectorNumber: { x: 5, y: 94, width: 40, height: 3 },
      artist: { x: 50, y: 94, width: 45, height: 3 },
    },
    fonts: {
      title: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 18,
        color: "#000000",
        textAlign: "left",
        fontWeight: "bold",
      },
      typeLine: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 16,
        color: "#000000",
        textAlign: "left",
        fontWeight: "bold",
      },
      rulesText: {
        fontFamily: "MPlantin, serif",
        fontSize: 15,
        color: "#000000",
        textAlign: "left",
        fontWeight: "normal",
      },
      flavorText: {
        fontFamily: "MPlantin, serif",
        fontSize: 14,
        color: "#000000",
        textAlign: "left",
        fontStyle: "italic",
        fontWeight: "normal",
      },
      pt: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 19,
        color: "#000000",
        textAlign: "center",
        fontWeight: "bold",
      },
      collectorNumber: {
        fontFamily: "MPlantin, serif",
        fontSize: 10,
        color: "#000000",
        textAlign: "left",
        fontWeight: "normal",
      },
      artist: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 10,
        color: "#000000",
        textAlign: "right",
        fontWeight: "normal",
      },
    },
  },
  {
    id: "showcase",
    name: "Showcase",
    frameImageUrl: showcaseFrame,
    elements: {
      title: { x: 5.5, y: 5, width: 55, height: 6 },
      manaCost: { x: 62, y: 5, width: 32, height: 6 },
      art: { x: 0, y: 0, width: 100, height: 65 },
      typeLine: { x: 5.5, y: 59, width: 75, height: 6 },
      setSymbol: { x: 84.5, y: 59.5, width: 10, height: 5 },
      textBox: { x: 5.5, y: 66, width: 89, height: 26 },
      ptBox: { x: 78, y: 88.5, width: 16, height: 6 },
      collectorNumber: { x: 5, y: 94, width: 40, height: 3 },
      artist: { x: 50, y: 94, width: 45, height: 3 },
    },
    fonts: {
      title: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 18,
        color: "#FFFFFF",
        textAlign: "left",
        fontWeight: "bold",
      },
      typeLine: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 16,
        color: "#FFFFFF",
        textAlign: "left",
        fontWeight: "bold",
      },
      rulesText: {
        fontFamily: "MPlantin, serif",
        fontSize: 15,
        color: "#FFFFFF",
        textAlign: "left",
        fontWeight: "normal",
      },
      flavorText: {
        fontFamily: "MPlantin, serif",
        fontSize: 14,
        color: "#FFFFFF",
        textAlign: "left",
        fontStyle: "italic",
        fontWeight: "normal",
      },
      pt: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 19,
        color: "#FFFFFF",
        textAlign: "center",
        fontWeight: "bold",
      },
      collectorNumber: {
        fontFamily: "MPlantin, serif",
        fontSize: 10,
        color: "#FFFFFF",
        textAlign: "left",
        fontWeight: "normal",
      },
      artist: {
        fontFamily: "Beleren, sans-serif",
        fontSize: 10,
        color: "#FFFFFF",
        textAlign: "right",
        fontWeight: "normal",
      },
    },
  },
];

export const DEFAULT_CARD_DATA: CardData = {
  name: "AI Artificer",
  manaCost: "{2}{U}{U}",
  art: {
    // Změněno na lokální cesty
    original: "/images/art/ai_artificer_original.jpg",
    cropped: "/images/art/ai_artificer_cropped.jpg",
  },
  cardType: CardType.Creature,
  subtype: "Human Artificer",
  rulesText:
    "When AI Artificer enters the battlefield, you may create a 1/1 colorless Thopter artifact creature token with flying.\nTap: Add {C}.",
  flavorText:
    '"My creations are not merely tools; they are extensions of my will, given form by logic and light."',
  power: "2",
  toughness: "3",
  rarity: Rarity.Rare,
  artist: "Gemini Engine",
  collectorNumber: "042/250",
  templateId: "modern",
  setSymbolUrl: "/svgs/sets/unf.svg",
};

export const MANA_SYMBOLS: { [key: string]: string } = {
  // Základní barvy
  W: "/svgs/mana/W.svg",
  U: "/svgs/mana/U.svg",
  B: "/svgs/mana/B.svg",
  R: "/svgs/mana/R.svg",
  G: "/svgs/mana/G.svg",
  C: "/svgs/mana/C.svg",
  
  // Číselné symboly
  '0': "/svgs/mana/0.svg",
  '1': "/svgs/mana/1.svg",
  '2': "/svgs/mana/2.svg",
  '3': "/svgs/mana/3.svg",
  '4': "/svgs/mana/4.svg",
  '5': "/svgs/mana/5.svg",
  '6': "/svgs/mana/6.svg",
  '7': "/svgs/mana/7.svg",
  '8': "/svgs/mana/8.svg",
  '9': "/svgs/mana/9.svg",
  '10': "/svgs/mana/10.svg",
  '11': "/svgs/mana/11.svg",
  '12': "/svgs/mana/12.svg",
  '13': "/svgs/mana/13.svg",
  '14': "/svgs/mana/14.svg",
  '15': "/svgs/mana/15.svg",
  X: "/svgs/mana/X.svg",
  
  // Speciální symboly
  T: "/svgs/mana/T.svg",
  UT: "/svgs/mana/UT.svg",
  H: "/svgs/mana/H.svg",
  
  // Phyrexian mana
  "W/P": "/svgs/mana/W_P.svg",
  "U/P": "/svgs/mana/U_P.svg",
  "B/P": "/svgs/mana/B_P.svg",
  "R/P": "/svgs/mana/R_P.svg",
  "G/P": "/svgs/mana/G_P.svg",
  
  // Hybridní mana
  "W/U": "/svgs/mana/W_U.svg",
  "W/B": "/svgs/mana/W_B.svg",
  "U/B": "/svgs/mana/U_B.svg",
  "U/R": "/svgs/mana/U_R.svg",
  "B/R": "/svgs/mana/B_R.svg",
  "B/G": "/svgs/mana/B_G.svg",
  "R/W": "/svgs/mana/R_W.svg",
  "R/G": "/svgs/mana/R_G.svg",
  "G/W": "/svgs/mana/G_W.svg",
  "G/U": "/svgs/mana/G_U.svg",
};

export const SET_SYMBOLS: { [key: string]: { name: string; url: string } } = {
  blb: { name: "Bloomburrow", url: "/svgs/sets/blb.svg" },
  mh3: { name: "Modern Horizons 3", url: "/svgs/sets/mh3.svg" },
  otj: { name: "Outlaws of Thunder Junction", url: "/svgs/sets/otj.svg" },
  mkm: { name: "Murders at Karlov Manor", url: "/svgs/sets/mkm.svg" },
  lci: { name: "The Lost Caverns of Ixalan", url: "/svgs/sets/lci.svg" },
  woe: { name: "Wilds of Eldraine", url: "/svgs/sets/woe.svg" },
  mom: { name: "March of the Machine", url: "/svgs/sets/mom.svg" },
  one: { name: "Phyrexia: All Will Be One", url: "/svgs/sets/one.svg" },
  bro: { name: "The Brothers' War", url: "/svgs/sets/bro.svg" },
  dmu: { name: "Dominaria United", url: "/svgs/sets/dmu.svg" },
  snc: { name: "Streets of New Capenna", url: "/svgs/sets/snc.svg" },
  neo: { name: "Kamigawa: Neon Dynasty", url: "/svgs/sets/neo.svg" },
  vow: { name: "Innistrad: Crimson Vow", url: "/svgs/sets/vow.svg" },
  mid: { name: "Innistrad: Midnight Hunt", url: "/svgs/sets/mid.svg" },
  afr: { name: "Adventures in the Forgotten Realms", url: "/svgs/sets/afr.svg" },
  stx: { name: "Strixhaven: School of Mages", url: "/svgs/sets/stx.svg" },
  khm: { name: "Kaldheim", url: "/svgs/sets/khm.svg" },
  znr: { name: "Zendikar Rising", url: "/svgs/sets/znr.svg" },
  eld: { name: "Throne of Eldraine", url: "/svgs/sets/eld.svg" },
  war: { name: "War of the Spark", url: "/svgs/sets/war.svg" },
  rna: { name: "Ravnica Allegiance", url: "/svgs/sets/rna.svg" },
  grn: { name: "Guilds of Ravnica", url: "/svgs/sets/grn.svg" },
  dom: { name: "Dominaria", url: "/svgs/sets/dom.svg" },
  xln: { name: "Ixalan", url: "/svgs/sets/xln.svg" },
  hou: { name: "Hour of Devastation", url: "/svgs/sets/hou.svg" },
  akh: { name: "Amonkhet", url: "/svgs/sets/akh.svg" },
  kld: { name: "Kaladesh", url: "/svgs/sets/kld.svg" },
  soi: { name: "Shadows over Innistrad", url: "/svgs/sets/soi.svg" },
  bfz: { name: "Battle for Zendikar", url: "/svgs/sets/bfz.svg" },
  ktk: { name: "Khans of Tarkir", url: "/svgs/sets/ktk.svg" },
  ths: { name: "Theros", url: "/svgs/sets/ths.svg" },
  rtr: { name: "Return to Ravnica", url: "/svgs/sets/rtr.svg" },
  isd: { name: "Innistrad", url: "/svgs/sets/isd.svg" },
  som: { name: "Scars of Mirrodin", url: "/svgs/sets/som.svg" },
  lrw: { name: "Lorwyn", url: "/svgs/sets/lrw.svg" },
  tsp: { name: "Time Spiral", url: "/svgs/sets/tsp.svg" },
  rav: { name: "Ravnica: City of Guilds", url: "/svgs/sets/rav.svg" },
  mrd: { name: "Mirrodin", url: "/svgs/sets/mrd.svg" },
  m21: { name: "Core Set 2021", url: "/svgs/sets/m21.svg" },
  m20: { name: "Core Set 2020", url: "/svgs/sets/m20.svg" },
  m19: { name: "Core Set 2019", url: "/svgs/sets/m19.svg" },
  ori: { name: "Magic Origins", url: "/svgs/sets/ori.svg" },
  cmm: { name: "Commander Masters", url: "/svgs/sets/cmm.svg" },
  ltr: { name: "The Lord of the Rings: Tales of Middle-earth", url: "/svgs/sets/ltr.svg", },
  clb: { name: "Commander Legends: Battle for Baldur's Gate", url: "/svgs/sets/clb.svg", },
  mh2: { name: "Modern Horizons 2", url: "/svgs/sets/mh2.svg" },
  cmr: { name: "Commander Legends", url: "/svgs/sets/cmr.svg" },
  "2xm": { name: "Double Masters", url: "/svgs/sets/2xm.svg" },
  mh1: { name: "Modern Horizons", url: "/svgs/sets/mh1.svg" },
  uma: { name: "Ultimate Masters", url: "/svgs/sets/uma.svg" },
  ema: { name: "Eternal Masters", url: "/svgs/sets/ema.svg" },
  mm3: { name: "Modern Masters 2017", url: "/svgs/sets/mm3.svg" },
  pip: { name: "Fallout", url: "/svgs/sets/pip.svg" },
  who: { name: "Doctor Who", url: "/svgs/sets/who.svg" },
  "40k": { name: "Warhammer 40,000", url: "/svgs/sets/40k.svg" },
  unf: { name: "Unfinity", url: "/svgs/sets/unf.svg" },
  ust: { name: "Unstable", url: "/svgs/sets/ust.svg" },
  usg: { name: "Urza's Saga", url: "/svgs/sets/usg.svg" },
  tmp: { name: "Tempest", url: "/svgs/sets/tmp.svg" },
  mir: { name: "Mirage", url: "/svgs/sets/mir.svg" },
  ice: { name: "Ice Age", url: "/svgs/sets/ice.svg" },
  fem: { name: "Fallen Empires", url: "/svgs/sets/fem.svg" },
  drk: { name: "The Dark", url: "/svgs/sets/drk.svg" },
  leg: { name: "Legends", url: "/svgs/sets/leg.svg" },
  atq: { name: "Antiquities", url: "/svgs/sets/atq.svg" },
  arn: { name: "Arabian Nights", url: "/svgs/sets/arn.svg" },
  lea: { name: "Limited Edition Alpha", url: "/svgs/sets/lea.svg" },
  leb: { name: "Limited Edition Beta", url: "/svgs/sets/leb.svg" },
  "2ed": { name: "Unlimited Edition", url: "/svgs/sets/2ed.svg" },
  sld: { name: "Secret Lair Drop", url: "/svgs/sets/sld.svg" },
};

export const RARITY_COLORS: { [key in Rarity]: string } = {
  [Rarity.Common]: "#000000",
  [Rarity.Uncommon]: "#C0C0C0",
  [Rarity.Rare]: "#FFD700",
  [Rarity.Mythic]: "#FF8000",
};