# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:3001"
    environment:
      - JWT_SECRET=mojeSuperTajneHesloProTokeny12345
      - GEMINI_API_KEY=zde-vlozte-vas-realny-gemini-api-klic
    volumes:
      - ./server/uploads:/app/uploads
      - ./server-db:/app/database # <-- ZMĚNA ZDE: Vytvoříme složku pro databázi

volumes:
  server-db: {}